# Generated by Django 4.2.1 on 2023-05-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_ema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('custom', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
