# Generated by Django 4.2.1 on 2023-05-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_ema', '0003_category_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tgbot_ema.category', verbose_name='Категория'),
        ),
    ]
