# Generated by Django 4.2.1 on 2023-05-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_ema', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='tgbot_ema/images', verbose_name='Фото товара'),
        ),
    ]
