# Generated by Django 4.2.1 on 2023-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_ema', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
