# Generated by Django 4.2.1 on 2023-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_ema', '0007_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='tgbot_ema/images', verbose_name='Фото товара'),
        ),
    ]
