# Generated by Django 4.2.1 on 2023-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_ema', '0009_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
